### ISSUE TITLE
`SixelMethod.to_string` will fail if number of colors is greater than 256

### ISSUE THREAD

**Issue by paw-lu** [adzierzanowski/timg#2]
For some images, when using `SixelMethod().to_string`, I get:

```pytb
Traceback (most recent call last):
  File "/Users/pawlu/Documents/scratch/teimpy/image.py", line 155, in <module>
    output = timg.SixelMethod(pil_image).to_string()
  File "/Users/pawlu/Documents/scratch/teimpy/.venv/lib/python3.9/site-packages/timg/methods/sixel.py", line 40, in to_string
    for i, (_, color) in enumerate(self.image.getcolors(1e3)):
  File "/Users/pawlu/Documents/scratch/teimpy/.venv/lib/python3.9/site-packages/PIL/Image.py", line 1272, in getcolors
    return self.im.getcolors(maxcolors)
TypeError: integer argument expected, got float
```

This seems to be due to this line—which calls Pillow's `getcolors()`.

https://github.com/adzierzanowski/timg/blob/080f60f2a883ecc12fe0f4636aa7a1c835bb7c86/timg/methods/sixel.py#L40

[From the docs, this is caused by the `maxcolors` argument:](https://pillow.readthedocs.io/en/stable/reference/Image.html?highlight=getcolors#PIL.Image.Image.getcolors)

> maxcolors – Maximum number of colors. If this number is exceeded, this method returns None. The default limit is 256 colors.

---

Thanks for sharing your work!

**Comment by adzierzanowski** [comment]
Hi, thanks for the report! Could you please provide me an image which triggers this error?

**Comment by paw-lu** [comment]
[Yeah here's a minimal example](https://gist.github.com/paw-lu/2d252a92c3123e57d6f6a7ea7c776b07).

Thanks!

**Comment by adzierzanowski** [comment]
Alright, the first issue is that terminal emulators, if they support sixels, they support anywhere from 256 sixel color registers to infinity.

Another issue is that I didn't optimize much and using more registers makes the rendering painfully slow. At the very least, I should implement RLE which is supported by sixels but it's hard for me to find time to do this. This is the reason why I reduce colors to 16 registers when using `timg` as a command.

I've increased the max number and now it should be sufficient for any image but as it most definitely will worsen performance when using it as a module, I recommend using [libsixel](https://github.com/saitoha/libsixel) for any serious work instead of my draft-quality code ;) or reducing color span of the image in PIL (the `Renderer` class in `timg` provides a wrapper for this).

So the bug should now be gone, thanks once again for your input.
